name: todo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
